name: Build thesis.pdf

on:
  push:
    paths:
      - '**/*.tex'

permissions:
  contents: write

jobs:
  build-latex-file:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Check if main.pdf exists
        id: check_pdf
        run: |
          if [ -f main.pdf ]; then
            echo "::set-output name=pdf_exists::true"
          else
            echo "::set-output name=pdf_exists::false"
          fi

      - name: Compile main.tex
        if: steps.check_pdf.outputs.pdf_exists == 'false'
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Push main.pdf
        if: steps.check_pdf.outputs.pdf_exists == 'false'
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add main.pdf
          git add main.xmpdata
          git commit -m "Create main.pdf"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
  
      - name: Update thesis.pdf
        run: |
            if [ -f main.pdf ]; then
              mv main.pdf thesis.pdf
            fi

      - name: Push thesis.pdf
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Update thesis.pdf"
          git push
