name: Update README abstract

on:
  workflow_run:
    workflows: ["Update README sommario"]  # Triggers after the "Update README sommario" workflow finishes
    types:
      - completed

  push:
    paths:
      - "frontmatter/abstract.tex" # Trigger only when abstract.tex is modified

permissions:
  contents: write

jobs:
  update-readme-abstract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract abstract and update README.md
      run: |
        # Extract content between \begin{abstract} and \end{abstract}
        abstract_content=$(sed -n '/\\begin{abstract}/, /\\end{abstract}/p' frontmatter/abstract.tex | sed '1d;$d')

        # Escape special characters for safe use in sed
        abstract_content=$(printf '%s\n' "$abstract_content" | sed 's/[&/\]/\\&/g')

        # Replace content in README.md between the markers <!-- BEGIN ABSTRACT --> and <!-- END ABSTRACT -->
        sed -i '/<!-- BEGIN ABSTRACT -->/,/<!-- END ABSTRACT -->/c\<!-- BEGIN ABSTRACT -->\n'"$abstract_content"'\n<!-- END ABSTRACT -->' README.md

    - name: Commit changes
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README - abstract"
        git push
