name: Update README abstract

on:
  workflow_run:
    workflows: ["Update README sommario"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-readme-abstract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract abstract content
      id: extract_abstract
      run: |
        # Extract content between \begin{abstract} and \end{abstract}
        abstract_content=$(sed -n '/\\begin{abstract}/, /\\end{abstract}/p' frontmatter/abstract.tex | sed '1d;$d')

        # Escape special characters for safe use in sed
        abstract_content=$(printf '%s\n' "$abstract_content" | sed 's/[&/\]/\\&/g')

        # Save the abstract content to a file
        echo "$abstract_content" > abstract_content.txt

    - name: Check if README.md needs update
      id: check_update
      run: |
        # Extract the current abstract from README.md
        current_abstract=$(sed -n '/<!-- BEGIN ABSTRACT -->/,/<!-- END ABSTRACT -->/p' README.md | sed '1d;$d')

        # Compare the current abstract with the new abstract
        if cmp -s abstract_content.txt <(printf "%s\n" "$current_abstract"); then
          echo "No changes to abstract"
          echo "update_needed=false" >> $GITHUB_ENV
        else
          echo "Changes detected in abstract"
          echo "update_needed=true" >> $GITHUB_ENV
        fi

    - name: Update README.md
      if: env.update_needed == 'true'
      run: |
        # Replace content in README.md between the markers <!-- BEGIN ABSTRACT --> and <!-- END ABSTRACT -->
        sed -i '/<!-- BEGIN ABSTRACT -->/,/<!-- END ABSTRACT -->/c\<!-- BEGIN ABSTRACT -->\n'"$(cat abstract_content.txt)"'\n<!-- END ABSTRACT -->' README.md

    - name: Commit changes
      if: env.update_needed == 'true'
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README - abstract"
        git push
