name: Update README sommario

on:
  workflow_run:
    workflows: ["Build thesis.pdf"]  # Triggers after the "Build thesis.pdf" workflow finishes
    types:
      - completed

permissions:
  contents: write

jobs:
  update-readme-sommario:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract sommario content
      id: extract_sommario
      run: |
        # Extract content between \begin{abstract}[it] and \end{abstract}
        sommario_content=$(sed -n '/\\begin{abstract}\[it\]/, /\\end{abstract}/p' frontmatter/sommario.tex | sed '1d;$d')

        # Escape special characters for safe use in sed
        sommario_content=$(printf '%s\n' "$sommario_content" | sed 's/[&/\]/\\&/g')

        # Save the sommario content to a file
        echo "$sommario_content" > sommario_content.txt

    - name: Check if README.md needs update
      id: check_update
      run: |
        # Extract the current sommario from README.md
        current_sommario=$(sed -n '/<!-- BEGIN SOMMARIO -->/,/<!-- END SOMMARIO -->/p' README.md | sed '1d;$d')

        # Compare the current sommario with the new sommario
        if cmp -s sommario_content.txt <(printf "%s\n" "$current_sommario"); then
          echo "No changes to sommario"
          echo "update_needed=false" >> $GITHUB_ENV
        else
          echo "Changes detected in sommario"
          echo "update_needed=true" >> $GITHUB_ENV
        fi

    - name: Update README.md
      if: env.update_needed == 'true'
      run: |
        # Replace content in README.md between the markers <!-- BEGIN SOMMARIO --> and <!-- END SOMMARIO -->
        sed -i '/<!-- BEGIN SOMMARIO -->/,/<!-- END SOMMARIO -->/c\<!-- BEGIN SOMMARIO -->\n'"$(cat sommario_content.txt)"'\n<!-- END SOMMARIO -->' README.md

    - name: Commit changes
      if: env.update_needed == 'true'
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README - sommario"
        git push
